import type {Module} from "../integration/types";
import {convertToSpacedString} from "./theme_config";

const categoryNames: Record<string, string> = {
    Combat: "战斗",
    Player: "玩家",
    Movement: "移动",
    Render: "渲染",
    World: "世界",
    Misc: "杂项",
    Exploit: "漏洞",
    Fun: "娱乐",
    Client: "客户端",
};

const moduleNames: Record<string, string> = {
    AbortBreaking: "中止破坏",
    Aimbot: "自动瞄准",
    AirJump: "空中跳跃",
    Animations: "动画",
    AntiAFK: "防挂机",
    AntiBlind: "防致盲",
    AntiBot: "反假人",
    AntiBounce: "防反弹",
    AntiCactus: "防仙人掌",
    AntiExploit: "反漏洞",
    AntiHunger: "防饥饿",
    AntiLevitation: "防漂浮",
    AntiReducedDebugInfo: "完整调试信息",
    AntiStaff: "管理检测",
    AntiVoid: "防虚空",
    AttackEffects: "攻击特效",
    AutoAccount: "自动账号",
    AutoArmor: "自动穿甲",
    AutoBow: "自动弓箭",
    AutoBreak: "自动破坏",
    AutoBuff: "自动增益",
    AutoClicker: "自动连点",
    AutoConfig: "自动配置",
    AutoDisable: "自动关闭",
    AutoDodge: "自动闪避",
    AutoF5: "自动 F5",
    AutoFarm: "自动农场",
    AutoFish: "自动钓鱼",
    AutoLeave: "自动离开",
    AutoPlay: "自动开始",
    AutoQueue: "自动排队",
    AutoRespawn: "自动重生",
    AutoShop: "自动购物",
    AutoShoot: "自动射击",
    AutoTool: "自动工具",
    AutoTotem: "自动图腾",
    AutoWalk: "自动行走",
    AutoWeapon: "自动武器",
    AvoidHazards: "避开危险",
    Backtrack: "回溯",
    BedPlates: "床防护显示",
    BetterChat: "聊天增强",
    Blink: "闪现",
    BlockBounce: "方块反弹",
    BlockESP: "方块透视",
    BlockWalk: "方块行走",
    Breadcrumbs: "足迹轨迹",
    BungeeSpoofer: "Bungee 伪装",
    CameraClip: "镜头穿墙",
    CapeTransfer: "披风转移",
    Chams: "人物透视",
    ChestStealer: "箱子窃取",
    CivBreak: "快速挖掘",
    ClickGUI: "点击界面",
    ClickTp: "点击传送",
    ClientSpoofer: "客户端伪装",
    Clip: "穿墙",
    CombineMobs: "实体合并",
    ConsoleSpammer: "控制台刷屏",
    Criticals: "自动暴击",
    CrystalAura: "水晶光环",
    CustomAmbience: "自定义环境",
    Damage: "自伤",
    DankBobbing: "夸张摇晃",
    Debug: "调试",
    DebugRecorder: "调试记录器",
    Derp: "乱转",
    Disabler: "反作弊禁用",
    Eagle: "边缘潜行",
    ElytraFly: "鞘翅飞行",
    Enemies: "敌人管理",
    EntityControl: "实体控制",
    ESP: "实体透视",
    FakeLag: "假延迟",
    FastBreak: "快速破坏",
    FastPlace: "快速放置",
    FastUse: "快速使用",
    Fly: "飞行",
    Focus: "锁定目标",
    ForceUnicodeChat: "Unicode 聊天",
    FreeCam: "自由视角",
    Freeze: "冻结",
    FriendClicker: "点击好友",
    Fucker: "方块破坏器",
    FullBright: "全亮",
    GhostHand: "穿墙交互",
    HandDerp: "手部乱动",
    HighJump: "高跳",
    Hitbox: "命中框",
    HoleESP: "洞穴透视",
    HUD: "界面叠加",
    Ignite: "自动点燃",
    InventoryCleaner: "背包整理",
    InventoryMove: "背包移动",
    ItemESP: "物品透视",
    JumpEffect: "跳跃特效",
    KeepChatAfterDeath: "死亡保留聊天",
    KeepSprint: "保持疾跑",
    Kick: "自我踢出",
    KillAura: "杀戮光环",
    LiquidChat: "Liquid 聊天",
    LiquidPlace: "液体放置",
    LiquidWalk: "水上行走",
    LongJump: "长跳",
    MobOwners: "生物主人",
    MoreCarry: "更多携带",
    MurderMystery: "密室杀手",
    NameCollector: "名称收集",
    NameProtect: "名称保护",
    Nametags: "名称标签",
    NoBob: "禁用摇晃",
    NoClip: "无碰撞",
    NoFall: "防摔落",
    NoFOV: "固定视角",
    NoHurtCam: "禁用受伤晃动",
    NoJumpDelay: "无跳跃延迟",
    NoPitchLimit: "无俯仰限制",
    NoPush: "防推动",
    NoRotateSet: "防视角修改",
    NoSignRender: "不渲染告示牌",
    NoSlow: "无减速",
    NoSlowBreak: "无挖掘减速",
    NoSwing: "禁用挥手",
    NoWeather: "禁用天气",
    NoWeb: "防蜘蛛网",
    Notifier: "通知器",
    Nuker: "区域破坏",
    Parkour: "跑酷",
    PingSpoof: "Ping 伪装",
    Plugins: "插件探测",
    PortalMenu: "传送门菜单",
    ProjectilePuncher: "弹射物反击",
    QuickPerspectiveSwap: "快速切换视角",
    Reach: "长臂",
    ResourceSpoof: "资源包伪装",
    ReverseStep: "快速下落",
    Rotations: "旋转显示",
    SafeWalk: "安全行走",
    Scaffold: "自动搭路",
    ServerCrasher: "服务器崩溃器",
    SkinDerp: "皮肤乱动",
    SleepWalker: "睡眠行走",
    SmartEat: "智能进食",
    Sneak: "自动潜行",
    Spammer: "聊天刷屏",
    Speed: "速度",
    Spider: "爬墙",
    Sprint: "疾跑",
    Step: "自动上台阶",
    StorageESP: "容器透视",
    Strafe: "空中变向",
    SuperKnockback: "超级击退",
    SwingFix: "挥手修复",
    SwordBlock: "剑格挡",
    TargetStrafe: "绕目标移动",
    Teams: "队伍",
    Teleport: "传送",
    TerrainSpeed: "地形加速",
    TickBase: "Tick 缓冲",
    TimeShift: "时间偏移",
    Timer: "变速",
    TimerRange: "范围变速",
    Tracers: "追踪线",
    Trajectories: "弹道轨迹",
    TranslationFix: "翻译修复",
    TrueSight: "真实视野",
    VehicleBoost: "载具加速",
    VehicleControl: "载具控制",
    VehicleOneHit: "载具一击",
    Velocity: "击退控制",
    XRay: "矿物透视",
};

const settingNames: Record<string, string> = {
    Accuracy: "精度",
    Action: "动作",
    Active: "启用",
    Add: "添加",
    Aim: "瞄准",
    AimMode: "瞄准模式",
    AimTiming: "瞄准时机",
    Alpha: "透明度",
    Amount: "数量",
    Angle: "角度",
    AntiCheat: "反作弊",
    Armor: "护甲",
    Attack: "攻击",
    AutoBlock: "自动格挡",
    AutoDisable: "自动关闭",
    Background: "背景",
    Balance: "平衡",
    Bind: "按键",
    Blink: "闪现",
    Blocks: "方块",
    Blur: "模糊",
    Boolean: "开关",
    Boost: "加速",
    Bypass: "绕过",
    Chat: "聊天",
    Check: "检测",
    Color: "颜色",
    Combat: "战斗",
    Cooldown: "冷却",
    Count: "数量",
    Delay: "延迟",
    Direction: "方向",
    Distance: "距离",
    Enabled: "启用",
    Enemy: "敌人",
    Expand: "展开",
    FakeLag: "假延迟",
    Filter: "过滤",
    FOV: "视场角",
    Friends: "好友",
    Glow: "发光",
    Health: "血量",
    Height: "高度",
    Hidden: "隐藏",
    Hold: "按住",
    HurtTime: "受伤时间",
    Ignore: "忽略",
    Inventory: "背包",
    Key: "按键",
    Locked: "锁定",
    Mark: "标记",
    Max: "最大",
    Min: "最小",
    Mode: "模式",
    Move: "移动",
    Name: "名称",
    Only: "仅",
    Packet: "数据包",
    Packets: "数据包",
    Pitch: "俯仰角",
    Player: "玩家",
    Range: "范围",
    Radius: "半径",
    Random: "随机",
    Render: "渲染",
    Rotation: "旋转",
    Rotations: "旋转",
    Scale: "缩放",
    Search: "搜索",
    Silent: "静默",
    Size: "大小",
    Speed: "速度",
    Sprint: "疾跑",
    Strength: "强度",
    Style: "样式",
    Suffix: "后缀",
    Swing: "挥手",
    Target: "目标",
    Targets: "目标",
    Text: "文本",
    ThroughWalls: "穿墙",
    Ticks: "刻",
    Timeout: "超时",
    Timer: "变速",
    Value: "值",
    Velocity: "击退",
    Width: "宽度",
    X: "X",
    Y: "Y",
    Yaw: "偏航角",
};

const settingValues: Record<string, string> = {
    AAC: "AAC",
    Absolute: "绝对",
    Always: "总是",
    Automatic: "自动",
    Back: "后方",
    Basic: "基础",
    Both: "两者",
    Bottom: "底部",
    Cancel: "取消",
    Center: "居中",
    Client: "客户端",
    Cubecraft: "CubeCraft",
    Custom: "自定义",
    Default: "默认",
    Disabled: "禁用",
    Down: "向下",
    Dynamic: "动态",
    Enabled: "启用",
    Forward: "前方",
    Grim: "Grim",
    Hypixel: "Hypixel",
    Ignore: "忽略",
    Jump: "跳跃",
    Left: "左侧",
    Legit: "拟真",
    Matrix: "Matrix",
    Middle: "中间",
    Motion: "移动",
    None: "无",
    Normal: "普通",
    Off: "关闭",
    Old: "旧版",
    On: "开启",
    Packet: "数据包",
    Packets: "数据包",
    Right: "右侧",
    Simple: "简单",
    Smooth: "平滑",
    Static: "静态",
    Strict: "严格",
    Top: "顶部",
    Vanilla: "原版",
    Vulcan: "Vulcan",
    Watchdog: "Watchdog",
};

function normalizeSearchText(value: string): string {
    return value.toLowerCase().replaceAll(" ", "");
}

function displaySpaced(value: string, useSpacedNames: boolean): string {
    return useSpacedNames ? convertToSpacedString(value) : value;
}

function translateByTokens(value: string, dictionary: Record<string, string>, useSpacedNames = true): string {
    if (dictionary[value]) {
        return dictionary[value];
    }

    const spaced = displaySpaced(value, useSpacedNames);
    if (dictionary[spaced]) {
        return dictionary[spaced];
    }

    const translated = spaced
        .split(/([\s./:_-]+)/)
        .map((part) => dictionary[part] ?? part)
        .join("");

    return translated === value ? spaced : translated;
}

export function translateCategoryName(category: string): string {
    return categoryNames[category] ?? category;
}

export function translateModuleName(name: string, useSpacedNames: boolean): string {
    return moduleNames[name] ?? displaySpaced(name, useSpacedNames);
}

export function translateModuleAliases(aliases: string[], useSpacedNames: boolean): string[] {
    return aliases.map((alias) => moduleNames[alias] ?? displaySpaced(alias, useSpacedNames));
}

export function translateSettingName(name: string, useSpacedNames: boolean): string {
    return translateByTokens(name, settingNames, useSpacedNames);
}

export function translateSettingValue(value: string, useSpacedNames: boolean): string {
    return translateByTokens(value, settingValues, useSpacedNames);
}

export function moduleSearchTerms(module: Module, useSpacedNames: boolean): string[] {
    const visibleName = translateModuleName(module.name, useSpacedNames);
    const englishName = displaySpaced(module.name, useSpacedNames);
    const aliases = module.aliases.flatMap((alias) => [
        alias,
        displaySpaced(alias, useSpacedNames),
        moduleNames[alias] ?? "",
    ]);

    return [module.name, englishName, visibleName, module.category, translateCategoryName(module.category), ...aliases]
        .filter((term) => term.length > 0)
        .map(normalizeSearchText);
}

export function moduleMatchesQuery(module: Module, query: string, useSpacedNames: boolean): boolean {
    const normalizedQuery = normalizeSearchText(query);
    return moduleSearchTerms(module, useSpacedNames).some((term) => term.includes(normalizedQuery));
}
