org.gradle.jvmargs=-Xms1024m -Xmx4096m
org.gradle.daemon=false
loom.platform=neoforge

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
neo_version_range=[21.1.0,)
loader_version_range=[4,)
architectury_loom_version=1.7.416
yarn_mappings=1.21.1+build.3
yarn_mappings_patch_neoforge=1.21+build.6
kotlin_version=2.0.0
mc_authlib_version=1.4.1
mcef_version=2.2.0-1.21.1-neoforge
mcef_version_range=[2.2.0,)
viafabricplus_version=3.4.3
sodium_version=mc1.21-0.5.11

mod_id=liquidbounce
mod_name=LiquidBounce
mod_license=GNU General Public License v3.0
mod_version=0.11.0-neoforge
mod_group_id=net.ccbluex
mod_authors=CCBlueX
mod_description=A NeoForge 1.21.1 port of LiquidBounce.
